<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <Title>StereoDB</Title>
        <Description>Ultrafast and lightweight in-process memory database that supports: transactions, secondary indexes, persistence, and data size larger than memory.</Description>
        <TargetFramework>net8.0</TargetFramework>
        <Authors>Anton Moldovan</Authors>
        <Company>StereoDB</Company>
        <Version>0.4.0</Version>
        <Copyright>StereoDB@2024</Copyright>
        <Nullable>disable</Nullable>
        <IncludeSymbols>true</IncludeSymbols>
        <SymbolPackageFormat>snupkg</SymbolPackageFormat>
        <PackageLicenseFile>LICENSE</PackageLicenseFile>
        <PackageRequireLicenseAcceptance>true</PackageRequireLicenseAcceptance>
        <PackageIcon>stereo_db_icon.jpg</PackageIcon>
        <RepositoryUrl>https://github.com/StereoDB/StereoDB</RepositoryUrl>
        <PackageTags>memory-db, cache, key value store</PackageTags>
        <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <OtherFlags>$(OtherFlags) --test:GraphBasedChecking --test:ParallelOptimization --test:ParallelIlxGen</OtherFlags>
    </PropertyGroup>

    <ItemGroup>
        <Compile Include="AssemblyInfo.fs" />
        <Compile Include="Constants.fs" />
        <Compile Include="Infra\Utils.fs" />
        <Compile Include="Infra\SkipList.fs" />
        <Compile Include="Storage\StorageDomain.fs" />
        <Compile Include="Storage\Sqlite.fs" />
        <Compile Include="Storage\StorageLog.fs" />        
        <Compile Include="Storage\EntityAddressStore.fs" />        
        <Compile Include="Api\Types.fs" />        
        <Compile Include="Api\CSharp.fs" />
        <Compile Include="Api\FSharp.fs" />                
        <Compile Include="SecondaryIndex\ValueIndex.fs" />
        <Compile Include="SecondaryIndex\MultiValueIndex.fs" />
        <Compile Include="SecondaryIndex\RangeScanIndex.fs" />
        <Compile Include="Table\TableDomain.fs" />
        <Compile Include="Table\StereoDbTable.fs" />
        <Compile Include="StereoDbSettings.fs" />
        <Compile Include="StereoDb.fs" />
    </ItemGroup>    
    
    <ItemGroup>
        <None Include="../../LICENSE" Pack="true" Visible="false" PackagePath="" />
        <None Include="../../assets/stereo_db_icon.jpg" Pack="true" Visible="false" PackagePath="" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Update="FSharp.Core" Version="9.0.100" />
        <PackageReference Include="FsToolkit.ErrorHandling.IcedTasks" Version="4.18.0" />        
        <PackageReference Include="MessagePack" Version="2.5.192" />
        <PackageReference Include="Microsoft.FASTER.Core" Version="2.6.5" />        
        <PackageReference Include="Microsoft.IO.RecyclableMemoryStream" Version="3.0.1" />
        <PackageReference Include="RepoDb.Sqlite.Microsoft" Version="1.13.1" />
        <PackageReference Include="Serilog" Version="4.1.0" />
        <PackageReference Include="System.Text.RegularExpressions" Version="4.3.1" />
    </ItemGroup>

</Project>
