<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="SqlParser.fs" />
    <Compile Include="Sql.fs" />
    <Compile Include="SqlExtensions.fs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Update="FSharp.Core" Version="7.0.300" />
    <PackageReference Include="FParsec" Version="2.0.0-beta2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\StereoDB\StereoDB.fsproj" />
  </ItemGroup>

</Project>
