<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net8.0</TargetFramework>
    </PropertyGroup>

    <ItemGroup>
        <Compile Include="Contracts.fs" />
        <Compile Include="Serialization.fs" />
        <Compile Include="Program.fs" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="FsToolkit.ErrorHandling.IcedTasks" Version="4.18.0" />
      <PackageReference Include="MessagePack" Version="2.5.187" />
      <PackageReference Include="Microsoft.FASTER.Core" Version="2.6.5" />
      <PackageReference Include="Microsoft.IO.RecyclableMemoryStream" Version="3.0.1" />
    </ItemGroup>

</Project>
